AWSTemplateFormatVersion: 2010-09-09

Description: >
  This Cloudformation template creates Petclinic Microservices App Demo Server
  using the AMI of Clarusway (ami-0d13e3c7d5ce1a035). The AMI of Clarusway 
  Demo Server is published on North Virginia Region for educational purposes.
  User needs to select appropriate key name when launching the template.

Parameters:
  KeyPairName:
    Description: Enter the name of your Key Pair for SSH connections.
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must one of the existing EC2 KeyPair

Resources:
  PetclinicDemoSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH and HTTP for Petclinic Microservices
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9090
          ToPort: 9090
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8081
          ToPort: 8081
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8082
          ToPort: 8082
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8083
          ToPort: 8083
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8888
          ToPort: 8888
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9411
          ToPort: 9411
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 7979
          ToPort: 7979
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9091
          ToPort: 9091
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8761
          ToPort: 8761
          CidrIp: 0.0.0.0/0

  PetclinicDemoServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0d13e3c7d5ce1a035
      InstanceType: t2.medium
      KeyName: !Ref KeyPairName
      SecurityGroupIds:
        - !GetAtt PetclinicDemoSG.GroupId
      UserData:
        Fn::Base64: |
            #! /bin/bash
            hostnamectl set-hostname petclinic-demo-server
            cd /home/ec2-user/petclinic-microservices && docker-compose up -d
      Tags:                
        - Key: Name
          Value: !Sub Petclinic App Demo Server of ${AWS::StackName}
Outputs:
  PetclinicDemoServerAPIGateway:
    Description: Petclinic App URL
    Value: !Sub 
      - http://${PublicAddress}:8080
      - PublicAddress: !GetAtt PetclinicDemoServer.PublicDnsName
  